services:
  mysql-reactpj:
    image: mysql:8.0
    container_name: mysql-reactpj
    restart: unless-stopped

    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: reactpj
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass

    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-reactpj-data:/var/lib/mysql

    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]

volumes:
  mysql-reactpj-data: